import { APP_NAME, HOME_ROUTE } from "@/shared/config";
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: APP_NAME,
    short_name: APP_NAME,
    start_url: HOME_ROUTE,
    display: "standalone",
    // WARN: DESIGN.md § 5. Light `canvas`, and it cannot follow the theme — a manifest carries one value with no media variant, unlike the `themeColor` in `app/layout.tsx`. The launch splash is therefore light even for a dark install; the app itself paints correctly the moment the document does.
    background_color: "#fbf9f6",
    theme_color: "#fbf9f6",
    // INFO: `public/icons/*`, regenerated by `pnpm icons`. They stay outside the proxy matcher so an uninstalled client is not redirected to `/login` while fetching them.
    icons: [
      { src: "/icons/icon-180.png", sizes: "180x180", type: "image/png" },
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
