import { ensureEnv } from "@/shared/config";
import { A_SECOND, toDayKey } from "@/shared/lib";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { format, resolveConfig } from "prettier";
import { findMissingLunisolar, toHolidayEntries } from "../src/shared/holiday/resolve";
import {
  EARLIEST_HOLIDAY_YEAR,
  fetchHolidayYear,
  HOLIDAY_PORTAL_URL,
  HOLIDAY_SERVICE_KEY_ENV,
  normalizeServiceKey,
} from "../src/shared/holiday/restde";
import { HOLIDAYS, type HolidayEntry } from "../src/shared/lib/date/holiday-table";

// INFO: A budget for one year's twelve requests, not a per-request timeout. Far above the runtime's, because a CLI that waits is visible where a render is not, and a run that gives up on a slow afternoon simply has to be repeated.
const YEAR_DEADLINE = 60 * A_SECOND;

// INFO: REQUIREMENTS.md § 11.7. — 월력요항 lands around mid-year for the year following, so two years ahead is the furthest a run can ever confirm.
const FUTURE_YEARS = 2;

const FROM_FLAG = "--from=";

const CURRENT_YEAR = Number(toDayKey(Date.now()).slice(0, 4));

const TABLE_PATH = path.join(process.cwd(), "src", "shared", "lib", "date", "holiday-table.ts");
const TABLE_RELATIVE_PATH = path.relative(process.cwd(), TABLE_PATH);

const USAGE = `Usage: pnpm holidays [${FROM_FLAG}YYYY] [--help]

Rebuilds ${TABLE_RELATIVE_PATH} from 공공데이터포털 특일 정보 (한국천문연구원).

The app reads 특일 정보 itself at runtime (REQUIREMENTS.md § 11.7.), so this table is
the fallback it draws when that request does not arrive — not the source. Refreshing
it is how a reader keeps seeing correct 공휴일 through an outage or an expired key.

A plain run refetches ${CURRENT_YEAR}-${CURRENT_YEAR + FUTURE_YEARS} and leaves every earlier year in the table
untouched, so a routine regeneration cannot show settled history drifting.

${FROM_FLAG}YYYY widens that back to any year from ${EARLIEST_HOLIDAY_YEAR} onward, re-verifying those
older years against the API. That is how the table's hand-typed entries get
checked, and it is expected to produce a large diff the first time.

${HOLIDAY_SERVICE_KEY_ENV} must be set; see .env.example.`;

function readServiceKey(): string {
  try {
    return normalizeServiceKey(ensureEnv(HOLIDAY_SERVICE_KEY_ENV));
  } catch {
    throw new Error(
      `${HOLIDAY_SERVICE_KEY_ENV} is not set. Issue a 특일 정보 key at ${HOLIDAY_PORTAL_URL} and put it in .env.local.`,
    );
  }
}

function readFromYear(): number {
  const flag = process.argv.find((value) => value.startsWith(FROM_FLAG));

  if (!flag) {
    return CURRENT_YEAR;
  }

  const from = Number(flag.slice(FROM_FLAG.length));

  if (!Number.isInteger(from) || from < EARLIEST_HOLIDAY_YEAR || from > CURRENT_YEAR) {
    throw new Error(
      `${FROM_FLAG}${flag.slice(FROM_FLAG.length)} is not a year this table can be extended back to. Pass a year between ${EARLIEST_HOLIDAY_YEAR} and ${CURRENT_YEAR}, or drop the flag to refetch ${CURRENT_YEAR} onward.`,
    );
  }

  return from;
}

function renderSource(entries: Map<string, HolidayEntry>): string {
  const sorted = [...entries].sort(([a], [b]) => (a < b ? -1 : 1));
  const years = sorted.map(([dayKey]) => dayKey.slice(0, 4));
  const lines = sorted.map(
    ([dayKey, [name, isSubstitute]]) =>
      `  "${dayKey}": ["${name}"${isSubstitute ? ", true" : ""}],`,
  );

  return `// WARN: Generated by \`pnpm holidays\` from 공공데이터포털 특일 정보 (한국천문연구원) — a hand edit is lost on the next run.

import type { Optional } from "../nullish";

/**
 * \`[name]\`, or \`[name, true]\` for a 대체공휴일.
 *
 * WARN: One entry per day, so a date carrying two holidays writes both into the one
 * name joined by \` · \` — 2025-05-05 is 어린이날 and 부처님오신날, 2028-10-03 is 추석 and
 * 개천절. Splitting the field would buy nothing: the day is one red cell either way,
 * and the 대체공휴일 the collision produces is already its own dated entry.
 */
export type HolidayEntry = readonly [name: string, isSubstitute?: true];

/**
 * REQUIREMENTS.md § 11.7. ${years.at(0)} – ${years.at(-1)}, as a table rather than a derivation.
 *
 * WARN: The fallback rather than the source — the server reads 특일 정보 at runtime and
 * lays its answer for the mutable years over this, so what is written here is what a
 * reader sees only when that request does not arrive.
 *
 * WARN: 설날 · 추석 · 부처님오신날 are lunisolar, 대체공휴일 follows from wherever they
 * land, and an 임시공휴일 is a cabinet decree — so no arithmetic here can carry this
 * past the last year written out below, and a day outside it answers \`null\`.
 *
 * INFO: \`pnpm holidays\` refetches the current year and the two after it and carries
 * every other year over untouched, so a year outside that window moves only under an
 * explicit \`--from\` (REQUIREMENTS.md § 11.7.).
 */
export const HOLIDAYS: Record<string, Optional<HolidayEntry>> = {
${lines.join("\n")}
};
`;
}

function countYear(entries: Map<string, HolidayEntry>, year: number): number {
  return [...entries.keys()].filter((dayKey) => dayKey.startsWith(`${year}-`)).length;
}

async function main() {
  if (process.argv.includes("--help")) {
    console.log(USAGE);

    return;
  }

  const serviceKey = readServiceKey();
  const fromYear = readFromYear();
  const lastYear = CURRENT_YEAR + FUTURE_YEARS;
  const merged = new Map<string, HolidayEntry>();

  for (const [dayKey, entry] of Object.entries(HOLIDAYS)) {
    if (entry) {
      merged.set(dayKey, entry);
    }
  }

  console.log(
    `Refetching ${fromYear}-${lastYear}; earlier years keep what the table holds (${FROM_FLAG}YYYY widens this).`,
  );

  for (let year = fromYear; year <= lastYear; year += 1) {
    const items = await fetchHolidayYear(year, {
      serviceKey,
      signal: AbortSignal.timeout(YEAR_DEADLINE),
    });
    const entries = toHolidayEntries(items);

    // WARN: Coverage, never a row count. `--from` reaches years 월력요항 has not, and 특일 정보 answers those with its rule-derived fixed dates alone — nine or ten entries that would pass a `length > 0` test and overwrite a committed year with its lunisolar tail deleted.
    const missing = findMissingLunisolar(entries);

    if (missing.length > 0) {
      // WARN: Korea has no year without 설날 and 추석, so this is 월력요항 that has not been published yet — never a year whose holidays were withdrawn, and never a reason to drop what the table already holds.
      if (year <= CURRENT_YEAR) {
        throw new Error(
          `특일 정보 returned ${entries.size} 공휴일 and no ${missing.join(", ")} for ${year}, a year that has already begun — that is a broken request, not an unpublished one.`,
        );
      }

      console.log(
        `${year}: not published yet (${entries.size} 공휴일, no ${missing.join(", ")}), kept ${countYear(merged, year)} existing entries`,
      );
      continue;
    }

    for (const dayKey of [...merged.keys()]) {
      if (dayKey.startsWith(`${year}-`)) {
        merged.delete(dayKey);
      }
    }

    for (const [dayKey, entry] of entries) {
      merged.set(dayKey, entry);
    }

    console.log(`${year}: ${countYear(merged, year)} 공휴일 from 특일 정보`);
  }

  const config = await resolveConfig(TABLE_PATH);
  const next = await format(renderSource(merged), { ...config, filepath: TABLE_PATH });

  await writeFile(TABLE_PATH, next, "utf8");
  console.log(`Wrote ${merged.size} holidays to ${TABLE_RELATIVE_PATH}`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
